export enum RoadmapOperationType {
  NODE_CREATED = 'NODE_CREATED',
  NODE_UPDATED = 'NODE_UPDATED',
  NODE_DELETED = 'NODE_DELETED',
  NODE_MOVED = 'NODE_MOVED',
  EDGE_CREATED = 'EDGE_CREATED',
  EDGE_DELETED = 'EDGE_DELETED'
}
